#!/usr/bin/env python3
"""Generate Localizable.xcstrings and InfoPlist.xcstrings for ClassGod."""

import json
import os

# All localization keys with translations for 10 languages
# Source language: zh-Hans
# Target languages: en, zh-Hant, ja, ko, fr, de, es, ru, pt

TRANSLATIONS = {
    # MenuBarView
    "app.title": {
        "en": "ClassGod",
        "zh-Hant": "ClassGod",
        "ja": "ClassGod",
        "ko": "ClassGod",
        "fr": "ClassGod",
        "de": "ClassGod",
        "es": "ClassGod",
        "ru": "ClassGod",
        "pt": "ClassGod",
    },
    "error.title": {
        "en": "Error",
        "zh-Hant": "出錯了",
        "ja": "エラー",
        "ko": "오류",
        "fr": "Erreur",
        "de": "Fehler",
        "es": "Error",
        "ru": "Ошибка",
        "pt": "Erro",
    },
    "error.unknown": {
        "en": "Unknown error",
        "zh-Hant": "未知錯誤",
        "ja": "不明なエラー",
        "ko": "알 수 없는 오류",
        "fr": "Erreur inconnue",
        "de": "Unbekannter Fehler",
        "es": "Error desconocido",
        "ru": "Неизвестная ошибка",
        "pt": "Erro desconhecido",
    },
    "button.ok": {
        "en": "OK",
        "zh-Hant": "OK",
        "ja": "OK",
        "ko": "확인",
        "fr": "OK",
        "de": "OK",
        "es": "OK",
        "ru": "OK",
        "pt": "OK",
    },
    "button.open_settings": {
        "en": "Open Settings",
        "zh-Hant": "去設定",
        "ja": "設定を開く",
        "ko": "설정 열기",
        "fr": "Ouvrir les réglages",
        "de": "Einstellungen öffnen",
        "es": "Abrir ajustes",
        "ru": "Открыть настройки",
        "pt": "Abrir configurações",
    },
    "button.cancel": {
        "en": "Never mind",
        "zh-Hant": "算了",
        "ja": "やっぱりやめる",
        "ko": "됐어",
        "fr": "Laisse tomber",
        "de": "Vergiss es",
        "es": "Déjalo",
        "ru": "Да ладно",
        "pt": "Deixa pra lá",
    },
    "permission.required.title": {
        "en": "Permission denied",
        "zh-Hant": "權限沒給夠",
        "ja": "権限が足りない",
        "ko": "권한이 부족해",
        "fr": "Permission refusée",
        "de": "Berechtigung verweigert",
        "es": "Permiso denegado",
        "ru": "Недостаточно прав",
        "pt": "Permissão negada",
    },
    "permission.required.message": {
        "en": "How am I supposed to keep watch without Accessibility permission? Go to System Settings > Privacy & Security > Accessibility and turn it on.",
        "zh-Hant": "不給 Accessibility 權限我怎麼幫你放風？去 系統設定 > 隱私與安全性 > 輔助功能 裡打開",
        "ja": "アクセシビリティ権限なしで見張りできるわけないだろ？システム設定 > プライバシーとセキュリティ > アクセシビリティ でオンにして",
        "ko": "접근성 권한 없이 어떻게 감시하라고? 시스템 설정 > 개인정보 보호 및 보안 > 접근성 에서 켜줘",
        "fr": "Comment je suis censé faire le guet sans la permission Accessibilité ? Va dans Réglages Système > Confidentialité et sécurité > Accessibilité et active-la.",
        "de": "Wie soll ich ohne Barrierefreiheitsberechtigung Wache halten? Geh zu Systemeinstellungen > Datenschutz & Sicherheit > Bedienungshilfen und schalte es ein.",
        "es": "¿Cómo voy a vigilar sin permiso de Accesibilidad? Ve a Ajustes del Sistema > Privacidad y Seguridad > Accesibilidad y actívalo.",
        "ru": "Как я буду следить без разрешения Специальных возможностей? Зайди в Системные настройки > Конфиденциальность и безопасность > Специальные возможности и включи.",
        "pt": "Como vou ficar de olho sem permissão de Acessibilidade? Vá em Ajustes do Sistema > Privacidade e Segurança > Acessibilidade e ative.",
    },
    "delete.confirm.title": {
        "en": "Delete this?",
        "zh-Hant": "刪了這條？",
        "ja": "これ削除する？",
        "ko": "이거 지울까?",
        "fr": "Supprimer ça ?",
        "de": "Das löschen?",
        "es": "¿Borrar esto?",
        "ru": "Удалить это?",
        "pt": "Apagar isso?",
    },
    "delete.confirm.message": {
        "en": "Are you sure you want to delete \"%@\"? You won't be able to switch when the teacher comes.",
        "zh-Hant": "確定要刪 \"%@\" 嗎？刪了老師來了就沒法切了",
        "ja": "本当に \"%@\" を削除する？削除したら先生が来たとき切り替えられないぞ",
        "ko": "정말 \"%@\" 를 지울 거야? 지우면 선생님 왔을 때 못 바꿔",
        "fr": "Tu es sûr de vouloir supprimer \"%@\" ? Tu pourras plus changer quand le prof arrive.",
        "de": "Bist du sicher, dass du \"%@\" löschen willst? Wenn der Lehrer kommt, kannst du nicht mehr wechseln.",
        "es": "¿Seguro que quieres borrar \"%@\"? Cuando venga el profe no podrás cambiar.",
        "ru": "Точно удалить \"%@\"? Когда учитель придёт, не сможешь переключить.",
        "pt": "Tem certeza que quer apagar \"%@\"? Quando o professor vier não vai conseguir trocar.",
    },
    "button.delete": {
        "en": "Delete",
        "zh-Hant": "刪掉",
        "ja": "削除",
        "ko": "지우기",
        "fr": "Supprimer",
        "de": "Löschen",
        "es": "Borrar",
        "ru": "Удалить",
        "pt": "Apagar",
    },
    "empty.title": {
        "en": "No saved tabs yet",
        "zh-Hant": "還沒存過頁面",
        "ja": "まだページを保存してない",
        "ko": "아직 저장한 페이지 없음",
        "fr": "Aucun onglet enregistré",
        "de": "Noch keine Tabs gespeichert",
        "es": "Aún no hay pestañas guardadas",
        "ru": "Ещё нет сохранённых вкладок",
        "pt": "Nenhuma aba salva ainda",
    },
    "empty.subtitle": {
        "en": "Click \"Save Current Tab\" below to save the current webpage, so you can switch instantly when the teacher comes.",
        "zh-Hant": "點下面的\"保存當前頁面\"把當前網頁存下來，老師來了好秒切",
        "ja": "下の\"現在のタブを保存\"をクリックして今のページを保存しとけ、先生が来たら一発で切り替えられるぞ",
        "ko": "아래 \"현재 페이지 저장\"을 눌러서 지금 웹페이지를 저장해둬, 선생님 오면 순식간에 바꿀 수 있어",
        "fr": "Clique sur \"Enregistrer l'onglet actuel\" en bas pour sauvegarder la page, comme ça tu pourras switch instantanément quand le prof arrive.",
        "de": "Klick unten auf \"Aktuellen Tab speichern\" um die Seite zu speichern, damit du umschalten kannst wenn der Lehrer kommt.",
        "es": "Haz clic en \"Guardar pestaña actual\" abajo para guardar la página, así podrás cambiar al instante cuando venga el profe.",
        "ru": "Нажми \"Сохранить текущую вкладку\" снизу, чтобы сохранить страницу, и сможешь мгновенно переключить когда учитель придёт.",
        "pt": "Clique em \"Salvar aba atual\" abaixo para salvar a página, assim você pode trocar na hora quando o professor chegar.",
    },
    "button.save_current_tab": {
        "en": "Save Current Tab",
        "zh-Hant": "保存當前頁面",
        "ja": "現在のタブを保存",
        "ko": "현재 페이지 저장",
        "fr": "Enregistrer l'onglet actuel",
        "de": "Aktuellen Tab speichern",
        "es": "Guardar pestaña actual",
        "ru": "Сохранить текущую вкладку",
        "pt": "Salvar aba atual",
    },
    "button.settings": {
        "en": "Settings...",
        "zh-Hant": "設定...",
        "ja": "設定...",
        "ko": "설정...",
        "fr": "Réglages...",
        "de": "Einstellungen...",
        "es": "Ajustes...",
        "ru": "Настройки...",
        "pt": "Configurações...",
    },
    "button.automation": {
        "en": "Automation Permissions...",
        "zh-Hant": "自動化權限...",
        "ja": "自動化権限...",
        "ko": "자동화 권한...",
        "fr": "Permissions d'automatisation...",
        "de": "Automatisierungsberechtigungen...",
        "es": "Permisos de automatización...",
        "ru": "Разрешения автоматизации...",
        "pt": "Permissões de automação...",
    },
    "button.quit": {
        "en": "Peace out",
        "zh-Hant": "溜了",
        "ja": "退散",
        "ko": "나갈게",
        "fr": "Je me tire",
        "de": "Ich hau ab",
        "es": "Me largo",
        "ru": "Свалил",
        "pt": "Fui",
    },
    "context.open": {
        "en": "Open",
        "zh-Hant": "打開",
        "ja": "開く",
        "ko": "열기",
        "fr": "Ouvrir",
        "de": "Öffnen",
        "es": "Abrir",
        "ru": "Открыть",
        "pt": "Abrir",
    },
    "context.edit": {
        "en": "Edit",
        "zh-Hant": "編輯",
        "ja": "編集",
        "ko": "편집",
        "fr": "Modifier",
        "de": "Bearbeiten",
        "es": "Editar",
        "ru": "Изменить",
        "pt": "Editar",
    },
    "accessibility.check_permission": {
        "en": "Check permission status",
        "zh-Hant": "檢查權限狀態",
        "ja": "権限状態を確認",
        "ko": "권한 상태 확인",
        "fr": "Vérifier l'état des permissions",
        "de": "Berechtigungsstatus prüfen",
        "es": "Verificar estado de permisos",
        "ru": "Проверить статус разрешений",
        "pt": "Verificar status de permissões",
    },
    
    # AddTabView
    "edit_tab.title": {
        "en": "Edit",
        "zh-Hant": "改一下",
        "ja": "編集",
        "ko": "수정",
        "fr": "Modifier",
        "de": "Bearbeiten",
        "es": "Editar",
        "ru": "Изменить",
        "pt": "Editar",
    },
    "add_tab.title": {
        "en": "New Tab",
        "zh-Hant": "新建一條",
        "ja": "新規タブ",
        "ko": "새 탭",
        "fr": "Nouvel onglet",
        "de": "Neuer Tab",
        "es": "Nueva pestaña",
        "ru": "Новая вкладка",
        "pt": "Nova aba",
    },
    "field.title": {
        "en": "Title (whatever)",
        "zh-Hant": "標題（隨便填）",
        "ja": "タイトル（適当でOK）",
        "ko": "제목 (아무거나)",
        "fr": "Titre (n'importe quoi)",
        "de": "Titel (egal was)",
        "es": "Título (lo que sea)",
        "ru": "Название (любое)",
        "pt": "Título (qualquer um)",
    },
    "field.url": {
        "en": "Link",
        "zh-Hant": "連結",
        "ja": "リンク",
        "ko": "링크",
        "fr": "Lien",
        "de": "Link",
        "es": "Enlace",
        "ru": "Ссылка",
        "pt": "Link",
    },
    "field.browser": {
        "en": "Which Browser",
        "zh-Hant": "用哪個瀏覽器",
        "ja": "どのブラウザ",
        "ko": "어떤 브라우저",
        "fr": "Quel navigateur",
        "de": "Welcher Browser",
        "es": "Qué navegador",
        "ru": "Какой браузер",
        "pt": "Qual navegador",
    },
    "section.shortcut": {
        "en": "Shortcut",
        "zh-Hant": "快捷鍵",
        "ja": "ショートカット",
        "ko": "단축키",
        "fr": "Raccourci",
        "de": "Tastenkürzel",
        "es": "Atajo",
        "ru": "Горячая клавиша",
        "pt": "Atalho",
    },
    "shortcut.conflict.warning": {
        "en": "This shortcut is taken by someone else. You gonna steal it?",
        "zh-Hant": "這快捷鍵被別人占了，你要硬搶嗎？",
        "ja": "このショートカットは誰かに使われてるぞ。無理矢理奪うのか？",
        "ko": "이 단축키는 남이 쓰고 있어. 뺏을 거야?",
        "fr": "Ce raccourci est déjà pris. Tu vas le voler ?",
        "de": "Dieses Tastenkürzel ist bereits belegt. Willst du es klauen?",
        "es": "Este atajo ya está ocupado. ¿Vas a quitárselo?",
        "ru": "Эта горячая клавиша уже занята. Будешь отбирать?",
        "pt": "Este atalho já está ocupado. Vai roubar?",
    },
    "shortcut.conflict.title": {
        "en": "Shortcut Collision",
        "zh-Hant": "快捷鍵撞車了",
        "ja": "ショートカット衝突",
        "ko": "단축키 충돌",
        "fr": "Collision de raccourci",
        "de": "Tastenkürzel-Kollision",
        "es": "Colisión de atajo",
        "ru": "Конфликт горячих клавиш",
        "pt": "Colisão de atalho",
    },
    "shortcut.conflict.message": {
        "en": "Another tab is already using this shortcut. Overwrite it?",
        "zh-Hant": "已經有別的頁面用了這個快捷鍵，覆蓋掉？",
        "ja": "別のページが既にこのショートカットを使ってるぞ。上書きする？",
        "ko": "다른 페이지가 이미 이 단축키를 쓰고 있어. 덮어쓸까?",
        "fr": "Un autre onglet utilise déjà ce raccourci. L'écraser ?",
        "de": "Ein anderer Tab verwendet dieses Tastenkürzel bereits. Überschreiben?",
        "es": "Otra pestaña ya está usando este atajo. ¿Sobrescribir?",
        "ru": "Другая вкладка уже использует эту горячую клавишу. Перезаписать?",
        "pt": "Outra aba já está usando este atalho. Sobrescrever?",
    },
    "button.overwrite": {
        "en": "Overwrite",
        "zh-Hant": "覆蓋",
        "ja": "上書き",
        "ko": "덮어쓰기",
        "fr": "Écraser",
        "de": "Überschreiben",
        "es": "Sobrescribir",
        "ru": "Перезаписать",
        "pt": "Sobrescrever",
    },
    "button.save_changes": {
        "en": "Save Changes",
        "zh-Hant": "保存修改",
        "ja": "変更を保存",
        "ko": "변경사항 저장",
        "fr": "Enregistrer les modifications",
        "de": "Änderungen speichern",
        "es": "Guardar cambios",
        "ru": "Сохранить изменения",
        "pt": "Salvar alterações",
    },
    "button.add_tab": {
        "en": "Add Tab",
        "zh-Hant": "加一條",
        "ja": "タブを追加",
        "ko": "탭 추가",
        "fr": "Ajouter un onglet",
        "de": "Tab hinzufügen",
        "es": "Añadir pestaña",
        "ru": "Добавить вкладку",
        "pt": "Adicionar aba",
    },
    
    # ShortcutPicker
    "accessibility.record_shortcut": {
        "en": "Record shortcut",
        "zh-Hant": "錄個快捷鍵",
        "ja": "ショートカットを記録",
        "ko": "단축키 녹화",
        "fr": "Enregistrer le raccourci",
        "de": "Tastenkürzel aufzeichnen",
        "es": "Grabar atajo",
        "ru": "Записать горячую клавишу",
        "pt": "Gravar atalho",
    },
    "accessibility.press_combination": {
        "en": "Press your desired key combination",
        "zh-Hant": "按你想設的快捷鍵組合",
        "ja": "設定したいキー組み合わせを押して",
        "ko": "원하는 키 조합을 눌러줘",
        "fr": "Appuie sur la combinaison de touches souhaitée",
        "de": "Drück die gewünschte Tastenkombination",
        "es": "Presiona la combinación de teclas deseada",
        "ru": "Нажми желаемое сочетание клавиш",
        "pt": "Pressione a combinação de teclas desejada",
    },
    "accessibility.tap_to_record": {
        "en": "Tap to start recording a keyboard shortcut",
        "zh-Hant": "點一下開始錄快捷鍵",
        "ja": "タップしてキーボードショートカットの記録を開始",
        "ko": "탭해서 키보드 단축키 녹화 시작",
        "fr": "Tape pour commencer à enregistrer un raccourci clavier",
        "de": "Tippen um die Aufzeichnung eines Tastenkürzels zu starten",
        "es": "Toca para empezar a grabar un atajo de teclado",
        "ru": "Нажми, чтобы начать запись горячей клавиши",
        "pt": "Toque para começar a gravar um atalho de teclado",
    },
    "button.clear": {
        "en": "Clear",
        "zh-Hant": "清空",
        "ja": "クリア",
        "ko": "지우기",
        "fr": "Effacer",
        "de": "Löschen",
        "es": "Limpiar",
        "ru": "Очистить",
        "pt": "Limpar",
    },
    "shortcut.press": {
        "en": "Press shortcut...",
        "zh-Hant": "按快捷鍵...",
        "ja": "ショートカットを押して...",
        "ko": "단축키 누르기...",
        "fr": "Appuie sur le raccourci...",
        "de": "Tastenkürzel drücken...",
        "es": "Presiona atajo...",
        "ru": "Нажми горячую клавишу...",
        "pt": "Pressione atalho...",
    },
    "shortcut.tap_to_set": {
        "en": "Tap to set shortcut",
        "zh-Hant": "點一下設定快捷鍵",
        "ja": "タップしてショートカットを設定",
        "ko": "탭해서 단축키 설정",
        "fr": "Tape pour définir le raccourci",
        "de": "Tippen um Tastenkürzel festzulegen",
        "es": "Toca para establecer atajo",
        "ru": "Нажми, чтобы назначить горячую клавишу",
        "pt": "Toque para definir atalho",
    },
    
    # GeneralSettingsView
    "section.behavior": {
        "en": "Behavior",
        "zh-Hant": "行為",
        "ja": "動作",
        "ko": "동작",
        "fr": "Comportement",
        "de": "Verhalten",
        "es": "Comportamiento",
        "ru": "Поведение",
        "pt": "Comportamento",
    },
    "setting.switch_behavior": {
        "en": "Tab Switching",
        "zh-Hant": "切屏方式",
        "ja": "タブ切り替え",
        "ko": "탭 전환",
        "fr": "Changement d'onglet",
        "de": "Tab-Wechsel",
        "es": "Cambio de pestaña",
        "ru": "Переключение вкладок",
        "pt": "Mudança de aba",
    },
    "setting.url_match": {
        "en": "URL Matching",
        "zh-Hant": "URL 匹配",
        "ja": "URL マッチング",
        "ko": "URL 매칭",
        "fr": "Correspondance d'URL",
        "de": "URL-Übereinstimmung",
        "es": "Coincidencia de URL",
        "ru": "Сопоставление URL",
        "pt": "Correspondência de URL",
    },
    "setting.toast": {
        "en": "Show Toast Notifications",
        "zh-Hant": "顯示 Toast 通知",
        "ja": "Toast 通知を表示",
        "ko": "토스트 알림 표시",
        "fr": "Afficher les notifications Toast",
        "de": "Toast-Benachrichtigungen anzeigen",
        "es": "Mostrar notificaciones Toast",
        "ru": "Показывать Toast-уведомления",
        "pt": "Mostrar notificações Toast",
    },
    "setting.toast_duration": {
        "en": "Toast Duration:",
        "zh-Hant": "Toast 停留時間：",
        "ja": "Toast 表示時間：",
        "ko": "토스트 지속 시간：",
        "fr": "Durée du Toast :",
        "de": "Toast-Dauer:",
        "es": "Duración del Toast:",
        "ru": "Длительность Toast:",
        "pt": "Duração do Toast:",
    },
    "section.animation": {
        "en": "Animation",
        "zh-Hant": "動畫",
        "ja": "アニメーション",
        "ko": "애니메이션",
        "fr": "Animation",
        "de": "Animation",
        "es": "Animación",
        "ru": "Анимация",
        "pt": "Animação",
    },
    "setting.animation_speed": {
        "en": "Animation Speed",
        "zh-Hant": "動畫速度",
        "ja": "アニメーション速度",
        "ko": "애니메이션 속도",
        "fr": "Vitesse d'animation",
        "de": "Animationsgeschwindigkeit",
        "es": "Velocidad de animación",
        "ru": "Скорость анимации",
        "pt": "Velocidade da animação",
    },
    "animation.off_caption": {
        "en": "Turn off animations for maximum responsiveness.",
        "zh-Hant": "關掉動畫，反應最快。",
        "ja": "アニメーションをオフにして最速の反応を得る。",
        "ko": "애니메이션을 끄면 반응이 가장 빨라.",
        "fr": "Désactive les animations pour une réactivité maximale.",
        "de": "Animationen ausschalten für maximale Reaktionsgeschwindigkeit.",
        "es": "Apaga las animaciones para máxima capacidad de respuesta.",
        "ru": "Выключи анимации для максимальной отзывчивости.",
        "pt": "Desligue as animações para máxima responsividade.",
    },
    "section.launch": {
        "en": "Launch",
        "zh-Hant": "啟動",
        "ja": "起動",
        "ko": "실행",
        "fr": "Lancement",
        "de": "Start",
        "es": "Inicio",
        "ru": "Запуск",
        "pt": "Inicialização",
    },
    "setting.launch_at_login": {
        "en": "Launch at Login",
        "zh-Hant": "開機自啟動",
        "ja": "ログイン時に起動",
        "ko": "로그인 시 실행",
        "fr": "Lancer à la connexion",
        "de": "Beim Anmelden starten",
        "es": "Lanzar al iniciar sesión",
        "ru": "Запуск при входе",
        "pt": "Iniciar no login",
    },
    "setting.show_on_launch": {
        "en": "Show Panel on Launch",
        "zh-Hant": "啟動時展開面板",
        "ja": "起動時にパネルを表示",
        "ko": "실행 시 패널 표시",
        "fr": "Afficher le panneau au lancement",
        "de": "Panel beim Start anzeigen",
        "es": "Mostrar panel al iniciar",
        "ru": "Показывать панель при запуске",
        "pt": "Mostrar painel ao iniciar",
    },
    "launch.coming_soon": {
        "en": "Coming in a future update",
        "zh-Hant": "後續版本再說",
        "ja": "今後のアップデートで対応予定",
        "ko": "향후 업데이트에서 지원 예정",
        "fr": "Disponible dans une future mise à jour",
        "de": "Kommt in einem zukünftigen Update",
        "es": "Disponible en una actualización futura",
        "ru": "В следующем обновлении",
        "pt": "Disponível em uma atualização futura",
    },
    "section.safety": {
        "en": "Safety",
        "zh-Hant": "安全",
        "ja": "安全",
        "ko": "안전",
        "fr": "Sécurité",
        "de": "Sicherheit",
        "es": "Seguridad",
        "ru": "Безопасность",
        "pt": "Segurança",
    },
    "setting.confirm_delete": {
        "en": "Confirm Before Deleting a Tab",
        "zh-Hant": "刪頁面前確認一下",
        "ja": "タブ削除前に確認する",
        "ko": "탭 삭제 전 확인",
        "fr": "Confirmer avant de supprimer un onglet",
        "de": "Vor dem Löschen eines Tabs bestätigen",
        "es": "Confirmar antes de borrar una pestaña",
        "ru": "Подтверждать перед удалением вкладки",
        "pt": "Confirmar antes de apagar uma aba",
    },
    "setting.confirm_clear": {
        "en": "Confirm Before Clearing All Tabs",
        "zh-Hant": "清空前確認一下",
        "ja": "全タブ削除前に確認する",
        "ko": "전체 탭 삭제 전 확인",
        "fr": "Confirmer avant de tout supprimer",
        "de": "Vor dem Löschen aller Tabs bestätigen",
        "es": "Confirmar antes de borrar todas las pestañas",
        "ru": "Подтверждать перед очисткой всех вкладок",
        "pt": "Confirmar antes de apagar todas as abas",
    },
    "section.feedback": {
        "en": "Feedback",
        "zh-Hant": "反饋",
        "ja": "フィードバック",
        "ko": "피드백",
        "fr": "Retour",
        "de": "Feedback",
        "es": "Retroalimentación",
        "ru": "Обратная связь",
        "pt": "Feedback",
    },
    "setting.sound_effects": {
        "en": "Enable Sound Effects",
        "zh-Hant": "開啟音效",
        "ja": "効果音を有効にする",
        "ko": "효과음 켜기",
        "fr": "Activer les effets sonores",
        "de": "Soundeffekte aktivieren",
        "es": "Habilitar efectos de sonido",
        "ru": "Включить звуковые эффекты",
        "pt": "Ativar efeitos sonoros",
    },
    "setting.haptic": {
        "en": "Enable Haptic Feedback",
        "zh-Hant": "開啟震動",
        "ja": "触覚フィードバックを有効にする",
        "ko": "햅틱 피드백 켜기",
        "fr": "Activer le retour haptique",
        "de": "Haptisches Feedback aktivieren",
        "es": "Habilitar retroalimentación háptica",
        "ru": "Включить тактильную обратную связь",
        "pt": "Ativar feedback háptico",
    },
    
    # ShortcutsSettingsView
    "section.global_shortcut": {
        "en": "Global Shortcut",
        "zh-Hant": "呼出快捷鍵",
        "ja": "グローバルショートカット",
        "ko": "전역 단축키",
        "fr": "Raccourci global",
        "de": "Globales Tastenkürzel",
        "es": "Atajo global",
        "ru": "Глобальная горячая клавиша",
        "pt": "Atalho global",
    },
    "setting.show_panel": {
        "en": "Show Menu Bar Panel:",
        "zh-Hant": "呼出菜單欄面板：",
        "ja": "メニューバーパネルを表示：",
        "ko": "메뉴 바 패널 표시：",
        "fr": "Afficher le panneau de la barre de menu :",
        "de": "Menüleisten-Panel anzeigen:",
        "es": "Mostrar panel de la barra de menú:",
        "ru": "Показывать панель меню:",
        "pt": "Mostrar painel da barra de menu:",
    },
    "shortcut.press_keys": {
        "en": "Press keys...",
        "zh-Hant": "按快捷鍵...",
        "ja": "キーを押して...",
        "ko": "키 누르기...",
        "fr": "Appuie sur les touches...",
        "de": "Tasten drücken...",
        "es": "Presiona teclas...",
        "ru": "Нажми клавиши...",
        "pt": "Pressione teclas...",
    },
    "button.reset": {
        "en": "Reset",
        "zh-Hant": "重置",
        "ja": "リセット",
        "ko": "초기화",
        "fr": "Réinitialiser",
        "de": "Zurücksetzen",
        "es": "Restablecer",
        "ru": "Сбросить",
        "pt": "Redefinir",
    },
    "section.tips": {
        "en": "Tips",
        "zh-Hant": "小貼士",
        "ja": "ヒント",
        "ko": "팁",
        "fr": "Astuces",
        "de": "Tipps",
        "es": "Consejos",
        "ru": "Подсказки",
        "pt": "Dicas",
    },
    "tip.avoid_conflict": {
        "en": "Avoid conflicts with system shortcuts",
        "zh-Hant": "別跟系統快捷鍵撞車",
        "ja": "システムショートカットと競合しないように",
        "ko": "시스템 단축키와 충돌하지 않도록",
        "fr": "Évite les conflits avec les raccourcis système",
        "de": "Vermeide Konflikte mit System-Tastenkürzeln",
        "es": "Evita conflictos con atajos del sistema",
        "ru": "Избегай конфликтов с системными горячими клавишами",
        "pt": "Evite conflitos com atalhos do sistema",
    },
    "tip.per_tab_shortcuts": {
        "en": "Per-tab shortcuts are configured in the main panel",
        "zh-Hant": "每個頁面的快捷鍵在主面板裡設",
        "ja": "タブごとのショートカットはメインパネルで設定",
        "ko": "탭별 단축키는 메인 패널에서 설정",
        "fr": "Les raccourcis par onglet se configurent dans le panneau principal",
        "de": "Tab-spezifische Tastenkürzel werden im Hauptpanel konfiguriert",
        "es": "Los atajos por pestaña se configuran en el panel principal",
        "ru": "Горячие клавиши для вкладок настраиваются в главной панели",
        "pt": "Atalhos por aba são configurados no painel principal",
    },
    "tip.restart": {
        "en": "Restart the app after changing this shortcut",
        "zh-Hant": "改完最好重啟一下",
        "ja": "このショートカットを変更後はアプリを再起動しよう",
        "ko": "이 단축키를 바꾼 후에는 앱을 재시작하자",
        "fr": "Redémarre l'app après avoir changé ce raccourci",
        "de": "Starte die App nach Änderung dieses Tastenkürzels neu",
        "es": "Reinicia la app después de cambiar este atajo",
        "ru": "Перезапусти приложение после изменения этой горячей клавиши",
        "pt": "Reinicie o app depois de mudar este atalho",
    },
    "accessibility.record_global": {
        "en": "Record global shortcut",
        "zh-Hant": "錄全局快捷鍵",
        "ja": "グローバルショートカットを記録",
        "ko": "전역 단축키 녹화",
        "fr": "Enregistrer le raccourci global",
        "de": "Globales Tastenkürzel aufzeichnen",
        "es": "Grabar atajo global",
        "ru": "Записать глобальную горячую клавишу",
        "pt": "Gravar atalho global",
    },
    "accessibility.tap_to_start": {
        "en": "Tap to start recording",
        "zh-Hant": "點一下開始錄",
        "ja": "タップして記録開始",
        "ko": "탭해서 녹화 시작",
        "fr": "Tape pour commencer l'enregistrement",
        "de": "Tippen um Aufzeichnung zu starten",
        "es": "Toca para empezar a grabar",
        "ru": "Нажми, чтобы начать запись",
        "pt": "Toque para começar a gravar",
    },
    "shortcut.tip.caption": {
        "en": "Click the shortcut box above to record a new global shortcut for opening the ClassGod panel.",
        "zh-Hant": "點上面的快捷鍵框錄一個新的全局快捷鍵，用來呼出 ClassGod 面板。",
        "ja": "上のショートカットボックスをクリックして、ClassGod パネルを開く新しいグローバルショートカットを記録しよう。",
        "ko": "위의 단축키 상자를 클릭해서 ClassGod 패널을 여는 새로운 전역 단축키를 녹화해봐.",
        "fr": "Clique sur la boîte de raccourci ci-dessus pour enregistrer un nouveau raccourci global pour ouvrir le panneau ClassGod.",
        "de": "Klick auf das Tastenkürzel-Feld oben um ein neues globales Tastenkürzel für das Öffnen des ClassGod-Panels aufzuzeichnen.",
        "es": "Haz clic en el cuadro de atajo de arriba para grabar un nuevo atajo global para abrir el panel de ClassGod.",
        "ru": "Нажми на поле горячей клавиши сверху, чтобы записать новую глобальную горячую клавишу для открытия панели ClassGod.",
        "pt": "Clique na caixa de atalho acima para gravar um novo atalho global para abrir o painel do ClassGod.",
    },
    "shortcut.none": {
        "en": "None",
        "zh-Hant": "無",
        "ja": "なし",
        "ko": "없음",
        "fr": "Aucun",
        "de": "Keine",
        "es": "Ninguno",
        "ru": "Нет",
        "pt": "Nenhum",
    },
    "shortcut.key_format": {
        "en": "Key %d",
        "zh-Hant": "按鍵 %d",
        "ja": "キー %d",
        "ko": "키 %d",
        "fr": "Touche %d",
        "de": "Taste %d",
        "es": "Tecla %d",
        "ru": "Клавиша %d",
        "pt": "Tecla %d",
    },
    
    # AppearanceSettingsView
    "section.menu_bar_icon": {
        "en": "Menu Bar Icon",
        "zh-Hant": "菜單欄圖標",
        "ja": "メニューバーアイコン",
        "ko": "메뉴 바 아이콘",
        "fr": "Icône de la barre de menu",
        "de": "Menüleisten-Symbol",
        "es": "Icono de la barra de menú",
        "ru": "Иконка менюбара",
        "pt": "Ícone da barra de menu",
    },
    "setting.icon_style": {
        "en": "Icon Style",
        "zh-Hant": "圖標樣式",
        "ja": "アイコンスタイル",
        "ko": "아이콘 스타일",
        "fr": "Style d'icône",
        "de": "Symbolstil",
        "es": "Estilo de icono",
        "ru": "Стиль иконки",
        "pt": "Estilo do ícone",
    },
    "section.panel": {
        "en": "Panel",
        "zh-Hant": "面板",
        "ja": "パネル",
        "ko": "패널",
        "fr": "Panneau",
        "de": "Panel",
        "es": "Panel",
        "ru": "Панель",
        "pt": "Painel",
    },
    "setting.width": {
        "en": "Width:",
        "zh-Hant": "寬度：",
        "ja": "幅：",
        "ko": "너비：",
        "fr": "Largeur :",
        "de": "Breite:",
        "es": "Ancho:",
        "ru": "Ширина:",
        "pt": "Largura:",
    },
    "setting.max_height": {
        "en": "Max Height:",
        "zh-Hant": "最大高度：",
        "ja": "最大高さ：",
        "ko": "최대 높이：",
        "fr": "Hauteur max :",
        "de": "Max. Höhe:",
        "es": "Altura máxima:",
        "ru": "Макс. высота:",
        "pt": "Altura máxima:",
    },
    "setting.row_height": {
        "en": "Row Height:",
        "zh-Hant": "行高：",
        "ja": "行の高さ：",
        "ko": "행 높이：",
        "fr": "Hauteur de ligne :",
        "de": "Zeilenhöhe:",
        "es": "Altura de fila:",
        "ru": "Высота строки:",
        "pt": "Altura da linha:",
    },
    "setting.max_tabs": {
        "en": "Max Tabs Shown:",
        "zh-Hant": "最多顯示：",
        "ja": "最大表示数：",
        "ko": "최대 표시：",
        "fr": "Onglets max affichés :",
        "de": "Max. angezeigte Tabs:",
        "es": "Máx. pestañas mostradas:",
        "ru": "Макс. отображаемых вкладок:",
        "pt": "Máx. abas exibidas:",
    },
    "section.theme": {
        "en": "Theme",
        "zh-Hant": "主題",
        "ja": "テーマ",
        "ko": "테마",
        "fr": "Thème",
        "de": "Thema",
        "es": "Tema",
        "ru": "Тема",
        "pt": "Tema",
    },
    "setting.appearance": {
        "en": "Appearance",
        "zh-Hant": "外觀",
        "ja": "外観",
        "ko": "외관",
        "fr": "Apparence",
        "de": "Erscheinungsbild",
        "es": "Apariencia",
        "ru": "Внешний вид",
        "pt": "Aparência",
    },
    "section.display": {
        "en": "Display Options",
        "zh-Hant": "顯示選項",
        "ja": "表示オプション",
        "ko": "표시 옵션",
        "fr": "Options d'affichage",
        "de": "Anzeigeoptionen",
        "es": "Opciones de visualización",
        "ru": "Параметры отображения",
        "pt": "Opções de exibição",
    },
    "setting.show_browser_icon": {
        "en": "Show Browser Icons",
        "zh-Hant": "顯示瀏覽器圖標",
        "ja": "ブラウザアイコンを表示",
        "ko": "브라우저 아이콘 표시",
        "fr": "Afficher les icônes de navigateur",
        "de": "Browser-Symbole anzeigen",
        "es": "Mostrar iconos de navegador",
        "ru": "Показывать иконки браузеров",
        "pt": "Mostrar ícones de navegador",
    },
    "setting.show_shortcut_badge": {
        "en": "Show Shortcut Badges",
        "zh-Hant": "顯示快捷鍵徽章",
        "ja": "ショートカットバッジを表示",
        "ko": "단축키 배지 표시",
        "fr": "Afficher les badges de raccourci",
        "de": "Tastenkürzel-Abzeichen anzeigen",
        "es": "Mostrar insignias de atajo",
        "ru": "Показывать значки горячих клавиш",
        "pt": "Mostrar emblemas de atalho",
    },
    "setting.show_url_preview": {
        "en": "Show URL Preview",
        "zh-Hant": "顯示 URL 預覽",
        "ja": "URL プレビューを表示",
        "ko": "URL 미리보기 표시",
        "fr": "Afficher l'aperçu de l'URL",
        "de": "URL-Vorschau anzeigen",
        "es": "Mostrar vista previa de URL",
        "ru": "Показывать превью URL",
        "pt": "Mostrar pré-visualização de URL",
    },
    "setting.compact_mode": {
        "en": "Compact Mode",
        "zh-Hant": "緊湊模式",
        "ja": "コンパクトモード",
        "ko": "컴팩트 모드",
        "fr": "Mode compact",
        "de": "Kompaktmodus",
        "es": "Modo compacto",
        "ru": "Компактный режим",
        "pt": "Modo compacto",
    },
    
    # BrowserSettingsView
    "section.default_browser": {
        "en": "Default Browser",
        "zh-Hant": "默認瀏覽器",
        "ja": "デフォルトブラウザ",
        "ko": "기본 브라우저",
        "fr": "Navigateur par défaut",
        "de": "Standardbrowser",
        "es": "Navegador predeterminado",
        "ru": "Браузер по умолчанию",
        "pt": "Navegador padrão",
    },
    "setting.when_adding": {
        "en": "When Adding Manually",
        "zh-Hant": "手動添加時用",
        "ja": "手動追加時に使用",
        "ko": "수동 추가 시 사용",
        "fr": "Lors de l'ajout manuel",
        "de": "Bei manuellem Hinzufügen",
        "es": "Al añadir manualmente",
        "ru": "При ручном добавлении",
        "pt": "Ao adicionar manualmente",
    },
    "browser.auto_detect": {
        "en": "Auto-detect (none)",
        "zh-Hant": "自動探測（無）",
        "ja": "自動検出（なし）",
        "ko": "자동 감지（없음）",
        "fr": "Détection auto (aucun)",
        "de": "Auto-Erkennen (keiner)",
        "es": "Autodetectar (ninguno)",
        "ru": "Автоопределение (нет)",
        "pt": "Auto-detectar (nenhum)",
    },
    "browser.default_caption": {
        "en": "The default browser is used when you manually add a tab without a browser currently open.",
        "zh-Hant": "手動添加頁面且沒開瀏覽器時，用這個默認瀏覽器。",
        "ja": "手動でタブを追加する際にブラウザが開いていない場合、このデフォルトブラウザが使われる。",
        "ko": "수동으로 탭을 추가할 때 브라우저가 열려있지 않으면 이 기본 브라우저를 사용해.",
        "fr": "Le navigateur par défaut est utilisé quand tu ajoutes manuellement un onglet sans navigateur ouvert.",
        "de": "Der Standardbrowser wird verwendet wenn du manuell einen Tab hinzufügst ohne dass ein Browser geöffnet ist.",
        "es": "El navegador predeterminado se usa cuando añades manualmente una pestaña sin un navegador abierto.",
        "ru": "Браузер по умолчанию используется при ручном добавлении вкладки без открытого браузера.",
        "pt": "O navegador padrão é usado quando você adiciona manualmente uma aba sem um navegador aberto.",
    },
    "section.browser_not_running": {
        "en": "When Browser Not Running",
        "zh-Hant": "瀏覽器沒開時",
        "ja": "ブラウザが起動していない時",
        "ko": "브라우저가 실행 중이 아닐 때",
        "fr": "Quand le navigateur n'est pas lancé",
        "de": "Wenn Browser nicht läuft",
        "es": "Cuando el navegador no está ejecutándose",
        "ru": "Когда браузер не запущен",
        "pt": "Quando o navegador não está rodando",
    },
    "setting.behavior": {
        "en": "Behavior",
        "zh-Hant": "行為",
        "ja": "動作",
        "ko": "동작",
        "fr": "Comportement",
        "de": "Verhalten",
        "es": "Comportamiento",
        "ru": "Поведение",
        "pt": "Comportamento",
    },
    "browser.not_running_caption": {
        "en": "Determines what happens when you trigger a shortcut for a browser that is not currently running.",
        "zh-Hant": "瀏覽器沒開時按快捷鍵會發生什麼。",
        "ja": "現在起動していないブラウザのショートカットをトリガーした時に何が起こるかを決定する。",
        "ko": "현재 실행 중이 아닌 브라우저의 단축키를 눌렀을 때 어떤 일이 일어나는지 결정해.",
        "fr": "Détermine ce qui se passe quand tu déclenches un raccourci pour un navigateur qui n'est pas en cours d'exécution.",
        "de": "Bestimmt was passiert wenn du ein Tastenkürzel für einen Browser auslöst der momentan nicht läuft.",
        "es": "Determina qué sucede cuando activas un atajo para un navegador que no está ejecutándose.",
        "ru": "Определяет, что происходит при срабатывании горячей клавиши для браузера, который сейчас не запущен.",
        "pt": "Determina o que acontece quando você aciona um atalho para um navegador que não está rodando.",
    },
    "section.supported_browsers": {
        "en": "Supported Browsers",
        "zh-Hant": "支持的瀏覽器",
        "ja": "対応ブラウザ",
        "ko": "지원 브라우저",
        "fr": "Navigateurs supportés",
        "de": "Unterstützte Browser",
        "es": "Navegadores soportados",
        "ru": "Поддерживаемые браузеры",
        "pt": "Navegadores suportados",
    },
    "section.permissions": {
        "en": "Permissions",
        "zh-Hant": "權限",
        "ja": "権限",
        "ko": "권한",
        "fr": "Permissions",
        "de": "Berechtigungen",
        "es": "Permisos",
        "ru": "Разрешения",
        "pt": "Permissões",
    },
    "button.open_automation": {
        "en": "Open Automation Settings...",
        "zh-Hant": "打開自動化權限設定...",
        "ja": "自動化権限設定を開く...",
        "ko": "자동화 권한 설정 열기...",
        "fr": "Ouvrir les réglages d'automatisation...",
        "de": "Automatisierungseinstellungen öffnen...",
        "es": "Abrir ajustes de automatización...",
        "ru": "Открыть настройки автоматизации...",
        "pt": "Abrir configurações de automação...",
    },
    
    # AdvancedSettingsView
    "section.data_management": {
        "en": "Data Management",
        "zh-Hant": "數據管理",
        "ja": "データ管理",
        "ko": "데이터 관리",
        "fr": "Gestion des données",
        "de": "Datenverwaltung",
        "es": "Gestión de datos",
        "ru": "Управление данными",
        "pt": "Gerenciamento de dados",
    },
    "button.export": {
        "en": "Export Settings...",
        "zh-Hant": "導出設定...",
        "ja": "設定をエクスポート...",
        "ko": "설정 내보내기...",
        "fr": "Exporter les réglages...",
        "de": "Einstellungen exportieren...",
        "es": "Exportar ajustes...",
        "ru": "Экспорт настроек...",
        "pt": "Exportar configurações...",
    },
    "button.import": {
        "en": "Import Settings...",
        "zh-Hant": "導入設定...",
        "ja": "設定をインポート...",
        "ko": "설정 가져오기...",
        "fr": "Importer les réglages...",
        "de": "Einstellungen importieren...",
        "es": "Importar ajustes...",
        "ru": "Импорт настроек...",
        "pt": "Importar configurações...",
    },
    "button.reset_all": {
        "en": "Reset All Settings",
        "zh-Hant": "重置所有設定",
        "ja": "全設定をリセット",
        "ko": "모든 설정 초기화",
        "fr": "Réinitialiser tous les réglages",
        "de": "Alle Einstellungen zurücksetzen",
        "es": "Restablecer todos los ajustes",
        "ru": "Сбросить все настройки",
        "pt": "Redefinir todas as configurações",
    },
    "button.clear_all": {
        "en": "Clear All Saved Tabs",
        "zh-Hant": "清空所有保存的頁面",
        "ja": "保存済みタブを全削除",
        "ko": "저장된 모든 탭 삭제",
        "fr": "Effacer tous les onglets enregistrés",
        "de": "Alle gespeicherten Tabs löschen",
        "es": "Borrar todas las pestañas guardadas",
        "ru": "Очистить все сохранённые вкладки",
        "pt": "Apagar todas as abas salvas",
    },
    "section.debug": {
        "en": "Debug",
        "zh-Hant": "調試",
        "ja": "デバッグ",
        "ko": "디버그",
        "fr": "Débogage",
        "de": "Debuggen",
        "es": "Depuración",
        "ru": "Отладка",
        "pt": "Depuração",
    },
    "setting.debug_logging": {
        "en": "Enable Debug Logging",
        "zh-Hant": "開啟調試日誌",
        "ja": "デバッグログを有効にする",
        "ko": "디버그 로깅 켜기",
        "fr": "Activer le journal de débogage",
        "de": "Debug-Protokollierung aktivieren",
        "es": "Habilitar registro de depuración",
        "ru": "Включить отладочное логирование",
        "pt": "Ativar registro de depuração",
    },
    "debug.caption": {
        "en": "Debug logs are printed to Console.app",
        "zh-Hant": "調試日誌輸出到 Console.app",
        "ja": "デバッグログは Console.app に出力される",
        "ko": "디버그 로그는 Console.app 에 출력돼",
        "fr": "Les logs de débogage s'affichent dans Console.app",
        "de": "Debug-Protokolle werden in Console.app ausgegeben",
        "es": "Los registros de depuración se imprimen en Console.app",
        "ru": "Отладочные логи выводятся в Console.app",
        "pt": "Logs de depuração são impressos no Console.app",
    },
    "button.open_console": {
        "en": "Open Console.app",
        "zh-Hant": "打開 Console.app",
        "ja": "Console.app を開く",
        "ko": "Console.app 열기",
        "fr": "Ouvrir Console.app",
        "de": "Console.app öffnen",
        "es": "Abrir Console.app",
        "ru": "Открыть Console.app",
        "pt": "Abrir Console.app",
    },
    "section.about": {
        "en": "About",
        "zh-Hant": "關於",
        "ja": "について",
        "ko": "정보",
        "fr": "À propos",
        "de": "Über",
        "es": "Acerca de",
        "ru": "О приложении",
        "pt": "Sobre",
    },
    "about.version": {
        "en": "Version",
        "zh-Hant": "版本",
        "ja": "バージョン",
        "ko": "버전",
        "fr": "Version",
        "de": "Version",
        "es": "Versión",
        "ru": "Версия",
        "pt": "Versão",
    },
    "about.developer": {
        "en": "Developer",
        "zh-Hant": "開發者",
        "ja": "開発者",
        "ko": "개발자",
        "fr": "Développeur",
        "de": "Entwickler",
        "es": "Desarrollador",
        "ru": "Разработчик",
        "pt": "Desenvolvedor",
    },
    "reset.confirm.title": {
        "en": "Reset Settings?",
        "zh-Hant": "重置設定？",
        "ja": "設定をリセット？",
        "ko": "설정을 초기화할까?",
        "fr": "Réinitialiser les réglages ?",
        "de": "Einstellungen zurücksetzen?",
        "es": "¿Restablecer ajustes?",
        "ru": "Сбросить настройки?",
        "pt": "Redefinir configurações?",
    },
    "reset.confirm.message": {
        "en": "This will reset all settings to their default values. Your saved tabs will not be affected.",
        "zh-Hant": "這會重置所有設定成默認值。保存的頁面不會丟。",
        "ja": "全設定がデフォルト値にリセットされる。保存済みのタブには影響しない。",
        "ko": "모든 설정이 기본값으로 초기화돼. 저장한 탭은 안 지워져.",
        "fr": "Tous les réglages seront réinitialisés aux valeurs par défaut. Tes onglets enregistrés ne seront pas affectés.",
        "de": "Alle Einstellungen werden auf die Standardwerte zurückgesetzt. Deine gespeicherten Tabs sind davon nicht betroffen.",
        "es": "Todos los ajustes se restablecerán a sus valores predeterminados. Tus pestañas guardadas no se verán afectadas.",
        "ru": "Все настройки будут сброшены до значений по умолчанию. Сохранённые вкладки не пострадают.",
        "pt": "Todas as configurações serão redefinidas para os valores padrão. Suas abas salvas não serão afetadas.",
    },
    "clear.confirm.title": {
        "en": "Clear All Tabs?",
        "zh-Hant": "清空所有頁面？",
        "ja": "全タブを削除？",
        "ko": "모든 탭을 삭제할까?",
        "fr": "Effacer tous les onglets ?",
        "de": "Alle Tabs löschen?",
        "es": "¿Borrar todas las pestañas?",
        "ru": "Очистить все вкладки?",
        "pt": "Apagar todas as abas?",
    },
    "clear.confirm.message": {
        "en": "This will permanently delete all saved tabs and shortcuts. This cannot be undone.",
        "zh-Hant": "這會永久刪除所有保存的頁面和快捷鍵，刪了就沒了。",
        "ja": "保存済みの全タブとショートカットが永久に削除される。元に戻せない。",
        "ko": "저장된 모든 탭과 단축키가 영구 삭제돼. 되돌릴 수 없어.",
        "fr": "Tous les onglets et raccourcis enregistrés seront définitivement supprimés. Action irréversible.",
        "de": "Alle gespeicherten Tabs und Tastenkürzel werden dauerhaft gelöscht. Dies kann nicht rückgängig gemacht werden.",
        "es": "Todas las pestañas y atajos guardados se eliminarán permanentemente. No se puede deshacer.",
        "ru": "Все сохранённые вкладки и горячие клавиши будут безвозвратно удалены. Это нельзя отменить.",
        "pt": "Todas as abas e atalhos salvos serão permanentemente apagados. Não pode ser desfeito.",
    },
    "import.result.title": {
        "en": "Import Result",
        "zh-Hant": "導入結果",
        "ja": "インポート結果",
        "ko": "가져오기 결과",
        "fr": "Résultat de l'importation",
        "de": "Import-Ergebnis",
        "es": "Resultado de importación",
        "ru": "Результат импорта",
        "pt": "Resultado da importação",
    },
    "import.success": {
        "en": "Settings imported successfully.",
        "zh-Hant": "設定導入成功。",
        "ja": "設定のインポートに成功した。",
        "ko": "설정 가져오기 성공.",
        "fr": "Réglages importés avec succès.",
        "de": "Einstellungen erfolgreich importiert.",
        "es": "Ajustes importados exitosamente.",
        "ru": "Настройки успешно импортированы.",
        "pt": "Configurações importadas com sucesso.",
    },
    "import.failure": {
        "en": "Failed to import settings. The file may be corrupted or incompatible.",
        "zh-Hant": "導入失敗，文件可能壞了或者不兼容。",
        "ja": "インポートに失敗した。ファイルが壊れているか互換性がない可能性がある。",
        "ko": "가져오기 실패. 파일이 손상되었거나 호환되지 않을 수 있어.",
        "fr": "Échec de l'importation des réglages. Le fichier est peut-être corrompu ou incompatible.",
        "de": "Import der Einstellungen fehlgeschlagen. Die Datei ist möglicherweise beschädigt oder inkompatibel.",
        "es": "Error al importar ajustes. El archivo puede estar corrupto o ser incompatible.",
        "ru": "Не удалось импортировать настройки. Файл может быть повреждён или несовместим.",
        "pt": "Falha ao importar configurações. O arquivo pode estar corrompido ou incompatível.",
    },
    "about.release_notes": {
        "en": "Release Notes",
        "zh-Hant": "發行說明",
        "ja": "リリースノート",
        "ko": "릴리즈 노트",
        "fr": "Notes de version",
        "de": "Versionshinweise",
        "es": "Notas de lanzamiento",
        "ru": "Примечания к выпуску",
        "pt": "Notas de lançamento",
    },
    "about.github_repo": {
        "en": "GitHub Repository",
        "zh-Hant": "GitHub 倉庫",
        "ja": "GitHub リポジトリ",
        "ko": "GitHub 저장소",
        "fr": "Dépôt GitHub",
        "de": "GitHub-Repository",
        "es": "Repositorio de GitHub",
        "ru": "GitHub репозиторий",
        "pt": "Repositório do GitHub",
    },
    "about.github_profile": {
        "en": "Developer Profile",
        "zh-Hant": "開發者主頁",
        "ja": "開発者プロフィール",
        "ko": "개발자 프로필",
        "fr": "Profil du développeur",
        "de": "Entwicklerprofil",
        "es": "Perfil del desarrollador",
        "ru": "Профиль разработчика",
        "pt": "Perfil do desenvolvedor",
    },
    
    # TabListViewModel
    "toast.saved": {
        "en": "Saved \"%@\"",
        "zh-Hant": "已保存 \"%@\"",
        "ja": "\"%@\" を保存した",
        "ko": "\"%@\" 저장됨",
        "fr": "\"%@\" enregistré",
        "de": "\"%@\" gespeichert",
        "es": "\"%@\" guardado",
        "ru": "\"%@\" сохранено",
        "pt": "\"%@\" salvo",
    },
    "toast.updated": {
        "en": "Updated \"%@\"",
        "zh-Hant": "已更新 \"%@\"",
        "ja": "\"%@\" を更新した",
        "ko": "\"%@\" 업데이트됨",
        "fr": "\"%@\" mis à jour",
        "de": "\"%@\" aktualisiert",
        "es": "\"%@\" actualizado",
        "ru": "\"%@\" обновлено",
        "pt": "\"%@\" atualizado",
    },
    "toast.saved_current": {
        "en": "Current tab saved",
        "zh-Hant": "當前頁面已保存",
        "ja": "現在のタブを保存した",
        "ko": "현재 탭 저장됨",
        "fr": "Onglet actuel enregistré",
        "de": "Aktueller Tab gespeichert",
        "es": "Pestaña actual guardada",
        "ru": "Текущая вкладка сохранена",
        "pt": "Aba atual salva",
    },
    "toast.switched": {
        "en": "Switched to %@",
        "zh-Hant": "已切到 %@",
        "ja": "%@ に切り替えた",
        "ko": "%@ 로 전환됨",
        "fr": "Basculé vers %@",
        "de": "Zu %@ gewechselt",
        "es": "Cambiado a %@",
        "ru": "Переключено на %@",
        "pt": "Mudado para %@",
    },
    "error.no_browser": {
        "en": "No browser detected",
        "zh-Hant": "沒探測到瀏覽器",
        "ja": "ブラウザが検出されなかった",
        "ko": "브라우저 감지 안 됨",
        "fr": "Aucun navigateur détecté",
        "de": "Kein Browser erkannt",
        "es": "Ningún navegador detectado",
        "ru": "Браузер не обнаружен",
        "pt": "Nenhum navegador detectado",
    },
    "error.no_active_tab": {
        "en": "No active tab found",
        "zh-Hant": "沒找到活躍標籤",
        "ja": "アクティブなタブが見つからなかった",
        "ko": "활성 탭을 찾을 수 없음",
        "fr": "Aucun onglet actif trouvé",
        "de": "Kein aktiver Tab gefunden",
        "es": "No se encontró pestaña activa",
        "ru": "Активная вкладка не найдена",
        "pt": "Nenhuma aba ativa encontrada",
    },
    "error.save_failed": {
        "en": "Failed to save tab",
        "zh-Hant": "保存失敗",
        "ja": "タブの保存に失敗した",
        "ko": "탭 저장 실패",
        "fr": "Échec de l'enregistrement de l'onglet",
        "de": "Tab speichern fehlgeschlagen",
        "es": "Error al guardar pestaña",
        "ru": "Не удалось сохранить вкладку",
        "pt": "Falha ao salvar aba",
    },
    
    # BrowserDetector
    "error.no_frontmost_browser": {
        "en": "No supported browser is currently frontmost.",
        "zh-Hant": "當前最前面的不是支持的瀏覽器",
        "ja": "前面にあるのは対応ブラウザじゃない",
        "ko": "현재 맨 앞에 있는 브라우저는 지원하지 않아",
        "fr": "Aucun navigateur supporté n'est actuellement au premier plan.",
        "de": "Kein unterstützter Browser ist momentan im Vordergrund.",
        "es": "Ningún navegador soportado está actualmente al frente.",
        "ru": "На переднем плане нет поддерживаемого браузера.",
        "pt": "Nenhum navegador suportado está atualmente em primeiro plano.",
    },
    "error.applescript_failed": {
        "en": "AppleScript crashed: %@",
        "zh-Hant": "AppleScript 掛了：%@",
        "ja": "AppleScript がクラッシュした：%@",
        "ko": "AppleScript 오류：%@",
        "fr": "AppleScript a planté : %@",
        "de": "AppleScript abgestürzt: %@",
        "es": "AppleScript falló: %@",
        "ru": "AppleScript упал: %@",
        "pt": "AppleScript travou: %@",
    },
    "error.invalid_response": {
        "en": "Invalid response from browser.",
        "zh-Hant": "瀏覽器回的數據不對",
        "ja": "ブラウザからの返答がおかしい",
        "ko": "브라우저 응답이 이상해",
        "fr": "Réponse invalide du navigateur.",
        "de": "Ungültige Antwort vom Browser.",
        "es": "Respuesta inválida del navegador.",
        "ru": "Некорректный ответ от браузера.",
        "pt": "Resposta inválida do navegador.",
    },
    "error.timeout": {
        "en": "Browser did not respond in time.",
        "zh-Hant": "瀏覽器沒響應，超時了",
        "ja": "ブラウザが応答しなかった。タイムアウトだ",
        "ko": "브라우저가 응답 안 해. 타임아웃",
        "fr": "Le navigateur n'a pas répondu à temps.",
        "de": "Browser hat nicht rechtzeitig geantwortet.",
        "es": "El navegador no respondió a tiempo.",
        "ru": "Браузер не ответил вовремя. Таймаут.",
        "pt": "O navegador não respondeu a tempo.",
    },
    "error.create_applescript": {
        "en": "Failed to create AppleScript",
        "zh-Hant": "創建 AppleScript 失敗",
        "ja": "AppleScript の作成に失敗した",
        "ko": "AppleScript 생성 실패",
        "fr": "Échec de la création d'AppleScript",
        "de": "AppleScript erstellen fehlgeschlagen",
        "es": "Error al crear AppleScript",
        "ru": "Не удалось создать AppleScript",
        "pt": "Falha ao criar AppleScript",
    },
    
    # BrowserSwitcher
    "error.browser_not_running": {
        "en": "%@ is not running",
        "zh-Hant": "%@ 沒開",
        "ja": "%@ が起動してない",
        "ko": "%@ 가 실행 중이 아니야",
        "fr": "%@ n'est pas lancé",
        "de": "%@ läuft nicht",
        "es": "%@ no está ejecutándose",
        "ru": "%@ не запущен",
        "pt": "%@ não está rodando",
    },
    "error.browser_not_found": {
        "en": "Could not find %@",
        "zh-Hant": "找不到 %@",
        "ja": "%@ が見つからない",
        "ko": "%@ 를 찾을 수 없어",
        "fr": "Impossible de trouver %@",
        "de": "%@ konnte nicht gefunden werden",
        "es": "No se pudo encontrar %@",
        "ru": "Не удалось найти %@",
        "pt": "Não foi possível encontrar %@",
    },
    "error.launch_failed": {
        "en": "Failed to launch %@: %@",
        "zh-Hant": "啟動 %@ 失敗：%@",
        "ja": "%@ の起動に失敗した：%@",
        "ko": "%@ 실행 실패：%@",
        "fr": "Échec du lancement de %@ : %@",
        "de": "%@ starten fehlgeschlagen: %@",
        "es": "Error al lanzar %@: %@",
        "ru": "Не удалось запустить %@: %@",
        "pt": "Falha ao iniciar %@: %@",
    },
    "toast.launched": {
        "en": "Launched %@",
        "zh-Hant": "已啟動 %@",
        "ja": "%@ を起動した",
        "ko": "%@ 실행됨",
        "fr": "%@ lancé",
        "de": "%@ gestartet",
        "es": "%@ lanzado",
        "ru": "%@ запущен",
        "pt": "%@ iniciado",
    },
    "toast.switched_browser": {
        "en": "Switched to %@",
        "zh-Hant": "已切到 %@",
        "ja": "%@ に切り替えた",
        "ko": "%@ 로 전환됨",
        "fr": "Basculé vers %@",
        "de": "Zu %@ gewechselt",
        "es": "Cambiado a %@",
        "ru": "Переключено на %@",
        "pt": "Mudado para %@",
    },
    "toast.opened_url": {
        "en": "Opened URL in %@",
        "zh-Hant": "已在 %@ 打開連結",
        "ja": "%@ で URL を開いた",
        "ko": "%@ 에서 URL 열림",
        "fr": "URL ouverte dans %@",
        "de": "URL in %@ geöffnet",
        "es": "URL abierta en %@",
        "ru": "URL открыт в %@",
        "pt": "URL aberta no %@",
    },
    "error.create_script": {
        "en": "Failed to create AppleScript",
        "zh-Hant": "創建 AppleScript 失敗",
        "ja": "AppleScript の作成に失敗した",
        "ko": "AppleScript 생성 실패",
        "fr": "Échec de la création d'AppleScript",
        "de": "AppleScript erstellen fehlgeschlagen",
        "es": "Error al crear AppleScript",
        "ru": "Не удалось создать AppleScript",
        "pt": "Falha ao criar AppleScript",
    },
    
    # ClassGodApp
    "permission.alert.title": {
        "en": "ClassGod Needs Permissions",
        "zh-Hant": "ClassGod 要權限",
        "ja": "ClassGod に権限が必要だ",
        "ko": "ClassGod 에게 권한이 필요해",
        "fr": "ClassGod a besoin de permissions",
        "de": "ClassGod benötigt Berechtigungen",
        "es": "ClassGod necesita permisos",
        "ru": "ClassGod требуются разрешения",
        "pt": "ClassGod precisa de permissões",
    },
    "permission.alert.message": {
        "en": "ClassGod needs Accessibility and Automation permissions to detect browser tabs and switch to them. Please grant these permissions in System Settings.",
        "zh-Hant": "ClassGod 需要 Accessibility 和 Automation 權限才能幫你探測瀏覽器和切屏。去系統設定裡給一下。",
        "ja": "ClassGod はブラウザタブを検出して切り替えるために、アクセシビリティと自動化の権限が必要だ。システム設定で許可してくれ。",
        "ko": "ClassGod 가 브라우저 탭을 감지하고 전환하려면 접근성과 자동화 권한이 필요해. 시스템 설정에서 허용해줘.",
        "fr": "ClassGod a besoin des permissions Accessibilité et Automatisation pour détecter les onglets du navigateur et y basculer. Accorde ces permissions dans les Réglages Système.",
        "de": "ClassGod benötigt Barrierefreiheits- und Automatisierungsberechtigungen um Browser-Tabs zu erkennen und zu ihnen zu wechseln. Bitte erteile diese Berechtigungen in den Systemeinstellungen.",
        "es": "ClassGod necesita permisos de Accesibilidad y Automatización para detectar pestañas del navegador y cambiar a ellas. Concede estos permisos en Ajustes del Sistema.",
        "ru": "ClassGod требуются разрешения Специальных возможностей и Автоматизации для обнаружения вкладок браузера и переключения на них. Предоставь эти разрешения в Системных настройках.",
        "pt": "ClassGod precisa de permissões de Acessibilidade e Automação para detectar abas do navegador e alternar para elas. Conceda essas permissões nos Ajustes do Sistema.",
    },
    "button.go_settings": {
        "en": "Open Settings",
        "zh-Hant": "去設定",
        "ja": "設定を開く",
        "ko": "설정 열기",
        "fr": "Ouvrir les réglages",
        "de": "Einstellungen öffnen",
        "es": "Abrir ajustes",
        "ru": "Открыть настройки",
        "pt": "Abrir configurações",
    },
    "button.later": {
        "en": "Later",
        "zh-Hant": "等會兒",
        "ja": "後で",
        "ko": "나중에",
        "fr": "Plus tard",
        "de": "Später",
        "es": "Más tarde",
        "ru": "Потом",
        "pt": "Depois",
    },
    "tab.general": {
        "en": "General",
        "zh-Hant": "常規",
        "ja": "一般",
        "ko": "일반",
        "fr": "Général",
        "de": "Allgemein",
        "es": "General",
        "ru": "Общие",
        "pt": "Geral",
    },
    "tab.shortcuts": {
        "en": "Shortcuts",
        "zh-Hant": "快捷鍵",
        "ja": "ショートカット",
        "ko": "단축키",
        "fr": "Raccourcis",
        "de": "Tastenkürzel",
        "es": "Atajos",
        "ru": "Горячие клавиши",
        "pt": "Atalhos",
    },
    "tab.appearance": {
        "en": "Appearance",
        "zh-Hant": "外觀",
        "ja": "外観",
        "ko": "외관",
        "fr": "Apparence",
        "de": "Erscheinungsbild",
        "es": "Apariencia",
        "ru": "Внешний вид",
        "pt": "Aparência",
    },
    "tab.browser": {
        "en": "Browser",
        "zh-Hant": "瀏覽器",
        "ja": "ブラウザ",
        "ko": "브라우저",
        "fr": "Navigateur",
        "de": "Browser",
        "es": "Navegador",
        "ru": "Браузер",
        "pt": "Navegador",
    },
    "tab.advanced": {
        "en": "Advanced",
        "zh-Hant": "高級",
        "ja": "詳細",
        "ko": "고급",
        "fr": "Avancé",
        "de": "Erweitert",
        "es": "Avanzado",
        "ru": "Дополнительно",
        "pt": "Avançado",
    },
    
    # AppPreferences enums
    "switch.activate_existing": {
        "en": "Switch to existing tab if found",
        "zh-Hant": "找到就切過去",
        "ja": "見つけたらそこに切り替える",
        "ko": "찾으면 거기로 전환",
        "fr": "Basculer vers l'onglet existant si trouvé",
        "de": "Zu vorhandenem Tab wechseln wenn gefunden",
        "es": "Cambiar a pestaña existente si se encuentra",
        "ru": "Переключиться на существующую вкладку, если найдена",
        "pt": "Mudar para aba existente se encontrada",
    },
    "switch.always_new": {
        "en": "Always open in new tab",
        "zh-Hant": "永遠新開標籤",
        "ja": "常に新しいタブで開く",
        "ko": "항상 새 탭으로 열기",
        "fr": "Toujours ouvrir dans un nouvel onglet",
        "de": "Immer in neuem Tab öffnen",
        "es": "Siempre abrir en nueva pestaña",
        "ru": "Всегда открывать в новой вкладке",
        "pt": "Sempre abrir em nova aba",
    },
    "match.exact": {
        "en": "Exact URL match",
        "zh-Hant": "完全匹配",
        "ja": "完全一致",
        "ko": "정확히 일치",
        "fr": "Correspondance exacte d'URL",
        "de": "Exakte URL-Übereinstimmung",
        "es": "Coincidencia exacta de URL",
        "ru": "Точное совпадение URL",
        "pt": "Correspondência exata de URL",
    },
    "match.prefix": {
        "en": "Prefix match (recommended)",
        "zh-Hant": "前綴匹配（推薦）",
        "ja": "プレフィックス一致（推奨）",
        "ko": "접두사 매칭（추천）",
        "fr": "Correspondance de préfixe (recommandé)",
        "de": "Präfix-Übereinstimmung (empfohlen)",
        "es": "Coincidencia de prefijo (recomendado)",
        "ru": "Совпадение по префиксу (рекомендуется)",
        "pt": "Correspondência de prefixo (recomendado)",
    },
    "match.host_only": {
        "en": "Host only (e.g. google.com)",
        "zh-Hant": "只匹配域名（比如 google.com）",
        "ja": "ホストのみ（例：google.com）",
        "ko": "호스트만（예：google.com）",
        "fr": "Hôte uniquement (ex: google.com)",
        "de": "Nur Host (z.B. google.com)",
        "es": "Solo host (ej. google.com)",
        "ru": "Только хост (напр. google.com)",
        "pt": "Apenas host (ex: google.com)",
    },
    "not_running.launch_open": {
        "en": "Launch browser and open URL",
        "zh-Hant": "啟動瀏覽器並打開連結",
        "ja": "ブラウザを起動して URL を開く",
        "ko": "브라우저 실행하고 URL 열기",
        "fr": "Lancer le navigateur et ouvrir l'URL",
        "de": "Browser starten und URL öffnen",
        "es": "Lanzar navegador y abrir URL",
        "ru": "Запустить браузер и открыть URL",
        "pt": "Iniciar navegador e abrir URL",
    },
    "not_running.launch_only": {
        "en": "Launch browser only",
        "zh-Hant": "只啟動瀏覽器",
        "ja": "ブラウザのみ起動",
        "ko": "브라우저만 실행",
        "fr": "Lancer uniquement le navigateur",
        "de": "Nur Browser starten",
        "es": "Solo lanzar navegador",
        "ru": "Только запустить браузер",
        "pt": "Apenas iniciar navegador",
    },
    "not_running.do_nothing": {
        "en": "Do nothing",
        "zh-Hant": "啥也不幹",
        "ja": "何もしない",
        "ko": "아무것도 안 함",
        "fr": "Ne rien faire",
        "de": "Nichts tun",
        "es": "No hacer nada",
        "ru": "Ничего не делать",
        "pt": "Não fazer nada",
    },
    "icon.default": {
        "en": "Default (Link Circle)",
        "zh-Hant": "默認（圓圈連結）",
        "ja": "デフォルト（リンクサークル）",
        "ko": "기본（링크 원）",
        "fr": "Par défaut (cercle de lien)",
        "de": "Standard (Link-Kreis)",
        "es": "Predeterminado (círculo de enlace)",
        "ru": "По умолчанию (круг ссылки)",
        "pt": "Padrão (círculo de link)",
    },
    "icon.fill": {
        "en": "Link Circle Fill",
        "zh-Hant": "實心圓圈連結",
        "ja": "リンクサークル塗りつぶし",
        "ko": "링크 원 채우기",
        "fr": "Cercle de lien rempli",
        "de": "Link-Kreis gefüllt",
        "es": "Círculo de enlace relleno",
        "ru": "Круг ссылки залитый",
        "pt": "Círculo de link preenchido",
    },
    "icon.plain": {
        "en": "Link",
        "zh-Hant": "連結",
        "ja": "リンク",
        "ko": "링크",
        "fr": "Lien",
        "de": "Link",
        "es": "Enlace",
        "ru": "Ссылка",
        "pt": "Link",
    },
    "icon.bolt": {
        "en": "Lightning Bolt",
        "zh-Hant": "閃電",
        "ja": "稲妻",
        "ko": "번개",
        "fr": "Éclair",
        "de": "Blitz",
        "es": "Rayo",
        "ru": "Молния",
        "pt": "Raio",
    },
    "icon.eye": {
        "en": "Eye",
        "zh-Hant": "眼睛",
        "ja": "目",
        "ko": "눈",
        "fr": "Œil",
        "de": "Auge",
        "es": "Ojo",
        "ru": "Глаз",
        "pt": "Olho",
    },
    "theme.system": {
        "en": "Follow System",
        "zh-Hant": "跟隨系統",
        "ja": "システムに従う",
        "ko": "시스템 따라가기",
        "fr": "Suivre le système",
        "de": "System folgen",
        "es": "Seguir sistema",
        "ru": "Как в системе",
        "pt": "Seguir sistema",
    },
    "theme.light": {
        "en": "Light",
        "zh-Hant": "淺色",
        "ja": "ライト",
        "ko": "밝게",
        "fr": "Clair",
        "de": "Hell",
        "es": "Claro",
        "ru": "Светлая",
        "pt": "Claro",
    },
    "theme.dark": {
        "en": "Dark",
        "zh-Hant": "深色",
        "ja": "ダーク",
        "ko": "어둡게",
        "fr": "Sombre",
        "de": "Dunkel",
        "es": "Oscuro",
        "ru": "Тёмная",
        "pt": "Escuro",
    },
    "speed.instant": {
        "en": "Off (Instant)",
        "zh-Hant": "關掉（瞬間）",
        "ja": "オフ（即時）",
        "ko": "끔（즉시）",
        "fr": "Désactivé (instantané)",
        "de": "Aus (Sofort)",
        "es": "Apagado (instantáneo)",
        "ru": "Выкл. (мгновенно)",
        "pt": "Desligado (instantâneo)",
    },
    "speed.fast": {
        "en": "Fast",
        "zh-Hant": "快",
        "ja": "速い",
        "ko": "빠르게",
        "fr": "Rapide",
        "de": "Schnell",
        "es": "Rápido",
        "ru": "Быстро",
        "pt": "Rápido",
    },
    "speed.normal": {
        "en": "Normal",
        "zh-Hant": "正常",
        "ja": "普通",
        "ko": "보통",
        "fr": "Normal",
        "de": "Normal",
        "es": "Normal",
        "ru": "Нормально",
        "pt": "Normal",
    },
    
    # InfoPlist
    "plist.automation": {
        "en": "ClassGod needs to control Safari, Chrome, and Edge to detect and switch browser tabs.",
        "zh-Hant": "ClassGod 需要控制 Safari、Chrome 和 Edge 來探測和切換瀏覽器標籤。",
        "ja": "ClassGod は Safari、Chrome、Edge を制御してブラウザタブを検出・切り替える必要がある。",
        "ko": "ClassGod 는 Safari, Chrome, Edge 를 제어하여 브라우저 탭을 감지하고 전환해야 해.",
        "fr": "ClassGod doit contrôler Safari, Chrome et Edge pour détecter et basculer entre les onglets du navigateur.",
        "de": "ClassGod muss Safari, Chrome und Edge steuern um Browser-Tabs zu erkennen und zu wechseln.",
        "es": "ClassGod necesita controlar Safari, Chrome y Edge para detectar y cambiar entre pestañas del navegador.",
        "ru": "ClassGod необходимо управлять Safari, Chrome и Edge для обнаружения и переключения вкладок браузера.",
        "pt": "ClassGod precisa controlar Safari, Chrome e Edge para detectar e alternar entre abas do navegador.",
    },
    "plist.accessibility": {
        "en": "ClassGod needs Accessibility permission to detect the frontmost browser and switch to specific tabs.",
        "zh-Hant": "ClassGod 需要 Accessibility 權限來探測最前面的瀏覽器並切換到指定標籤。",
        "ja": "ClassGod は最前面のブラウザを検出して特定のタブに切り替えるために、アクセシビリティ権限が必要だ。",
        "ko": "ClassGod 는 맨 앞 브라우저를 감지하고 특정 탭으로 전환하기 위해 접근성 권한이 필요해.",
        "fr": "ClassGod a besoin de la permission Accessibilité pour détecter le navigateur au premier plan et basculer vers des onglets spécifiques.",
        "de": "ClassGod benötigt die Barrierefreiheitsberechtigung um den Browser im Vordergrund zu erkennen und zu bestimmten Tabs zu wechseln.",
        "es": "ClassGod necesita permiso de Accesibilidad para detectar el navegador al frente y cambiar a pestañas específicas.",
        "ru": "ClassGod требуется разрешение Специальных возможностей для обнаружения браузера на переднем плане и переключения на конкретные вкладки.",
        "pt": "ClassGod precisa de permissão de Acessibilidade para detectar o navegador em primeiro plano e alternar para abas específicas.",
    },
    
    # PreferencesManager
    "export.filename": {
        "en": "ClassGod-Settings-%@.json",
        "zh-Hant": "ClassGod-設定-%@.json",
        "ja": "ClassGod-設定-%@.json",
        "ko": "ClassGod-설정-%@.json",
        "fr": "ClassGod-Reglages-%@.json",
        "de": "ClassGod-Einstellungen-%@.json",
        "es": "ClassGod-Ajustes-%@.json",
        "ru": "ClassGod-Настройки-%@.json",
        "pt": "ClassGod-Configuracoes-%@.json",
    },
    
    # New settings
    "setting.show_tab_count": {
        "en": "Show Tab Count Badge",
        "zh-Hant": "顯示標籤數量徽章",
        "ja": "タブ数バッジを表示",
        "ko": "탭 수 배지 표시",
        "fr": "Afficher le badge de nombre d'onglets",
        "de": "Tab-Anzahl-Abzeichen anzeigen",
        "es": "Mostrar insignia de cantidad de pestañas",
        "ru": "Показывать значок количества вкладок",
        "pt": "Mostrar emblema de contagem de abas",
    },
    "setting.auto_detect": {
        "en": "Auto-detect Current Tab on Show",
        "zh-Hant": "顯示面板時自動探測",
        "ja": "表示時に現在のタブを自動検出",
        "ko": "패널 표시 시 현재 탭 자동 감지",
        "fr": "Détecter automatiquement l'onglet actuel à l'affichage",
        "de": "Aktuellen Tab beim Anzeigen automatisch erkennen",
        "es": "Detectar automáticamente pestaña actual al mostrar",
        "ru": "Автоопределять текущую вкладку при отображении",
        "pt": "Detectar automaticamente aba atual ao mostrar",
    },
    "setting.switch_delay": {
        "en": "Switch Delay (ms):",
        "zh-Hant": "切換延遲（毫秒）：",
        "ja": "切り替え遅延（ミリ秒）：",
        "ko": "전환 지연（밀리초）：",
        "fr": "Délai de basculement (ms) :",
        "de": "Wechselverzögerung (ms):",
        "es": "Retraso de cambio (ms):",
        "ru": "Задержка переключения (мс):",
        "pt": "Atraso de mudança (ms):",
    },
    "setting.corner_radius": {
        "en": "Panel Corner Radius:",
        "zh-Hant": "面板圓角：",
        "ja": "パネル角丸：",
        "ko": "패널 모서리 반경：",
        "fr": "Rayon des coins du panneau :",
        "de": "Panel-Eckenradius:",
        "es": "Radio de esquinas del panel:",
        "ru": "Радиус скругления панели:",
        "pt": "Raio de canto do painel:",
    },
    "setting.keyboard_nav": {
        "en": "Enable Keyboard Navigation",
        "zh-Hant": "啟用鍵盤導航",
        "ja": "キーボードナビゲーションを有効にする",
        "ko": "키보드 내비게이션 활성화",
        "fr": "Activer la navigation au clavier",
        "de": "Tastaturnavigation aktivieren",
        "es": "Habilitar navegación por teclado",
        "ru": "Включить навигацию с клавиатуры",
        "pt": "Ativar navegação por teclado",
    },
    "setting.instant_mode": {
        "en": "Ultra Speed Mode (Disable All Animations)",
        "zh-Hant": "極速模式（關閉所有動畫）",
        "ja": "ウルトラスピードモード（全アニメーション無効）",
        "ko": "초고속 모드（모든 애니메이션 비활성화）",
        "fr": "Mode ultra-rapide (désactiver toutes les animations)",
        "de": "Ultra-Geschwindigkeitsmodus (alle Animationen deaktivieren)",
        "es": "Modo ultra rápido (desactivar todas las animaciones)",
        "ru": "Ультраскоростной режим (отключить все анимации)",
        "pt": "Modo ultra rápido (desativar todas as animações)",
    },
    
    # Splash screen
    "splash.title": {
        "en": "Hanazar Products",
        "zh-Hant": "Hanazar Products",
        "ja": "Hanazar Products",
        "ko": "Hanazar Products",
        "fr": "Hanazar Products",
        "de": "Hanazar Products",
        "es": "Hanazar Products",
        "ru": "Hanazar Products",
        "pt": "Hanazar Products",
    },
    "splash.subtitle": {
        "en": "ClassGod",
        "zh-Hant": "ClassGod",
        "ja": "ClassGod",
        "ko": "ClassGod",
        "fr": "ClassGod",
        "de": "ClassGod",
        "es": "ClassGod",
        "ru": "ClassGod",
        "pt": "ClassGod",
    },
}

LANGUAGES = ["en", "zh-Hant", "ja", "ko", "fr", "de", "es", "ru", "pt"]
SOURCE_LANG = "zh-Hans"

def build_xcstrings():
    catalog = {
        "sourceLanguage": SOURCE_LANG,
        "strings": {},
        "version": "1.0"
    }
    
    for key, translations in TRANSLATIONS.items():
        source_value = translations.get(SOURCE_LANG, key)
        localizations = {}
        
        for lang in LANGUAGES:
            value = translations.get(lang, source_value)
            localizations[lang] = {
                "stringUnit": {
                    "state": "translated",
                    "value": value
                }
            }
        
        catalog["strings"][key] = {
            "localizations": localizations
        }
    
    return catalog

def build_infoplist_xcstrings():
    catalog = {
        "sourceLanguage": SOURCE_LANG,
        "strings": {},
        "version": "1.0"
    }
    
    plist_keys = {
        "NSAppleEventsUsageDescription": "plist.automation",
        "NSAccessibilityUsageDescription": "plist.accessibility",
    }
    
    for plist_key, loc_key in plist_keys.items():
        translations = TRANSLATIONS[loc_key]
        source_value = translations.get(SOURCE_LANG, loc_key)
        localizations = {}
        
        for lang in LANGUAGES:
            value = translations.get(lang, source_value)
            localizations[lang] = {
                "stringUnit": {
                    "state": "translated",
                    "value": value
                }
            }
        
        catalog["strings"][plist_key] = {
            "localizations": localizations
        }
    
    return catalog

def main():
    base = "/Users/charliezhong/Documents/Github/ClassGod/ClassGod/ClassGod"
    
    # Write Localizable.xcstrings
    localizable = build_xcstrings()
    with open(os.path.join(base, "Localizable.xcstrings"), "w", encoding="utf-8") as f:
        json.dump(localizable, f, ensure_ascii=False, indent=2)
    
    # Write InfoPlist.xcstrings
    infoplist = build_infoplist_xcstrings()
    with open(os.path.join(base, "InfoPlist.xcstrings"), "w", encoding="utf-8") as f:
        json.dump(infoplist, f, ensure_ascii=False, indent=2)
    
    print(f"Generated Localizable.xcstrings with {len(localizable['strings'])} keys")
    print(f"Generated InfoPlist.xcstrings with {len(infoplist['strings'])} keys")

if __name__ == "__main__":
    main()
